-- Create database
CREATE DATABASE IF NOT EXISTS KAFKA_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS KAFKA_DB.STREAMING;

-- Create warehouse (if not exists)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
WITH WAREHOUSE_SIZE = 'X-SMALL' 
AUTO_SUSPEND = 300 
AUTO_RESUME = TRUE;

-- Use the database and schema
USE DATABASE KAFKA_DB;
USE SCHEMA STREAMING;
USE WAREHOUSE COMPUTE_WH;