USE DATABASE KAFKA_DB;
USE SCHEMA STREAMING;

CREATE TABLE IF NOT EXISTS KAFKA_DAILY_METRICS_GOLD (
    METRIC_DATE DATE,
    CUSTOMER_ID VARCHAR(20),
    TOTAL_AMOUNT DECIMAL(15,2),
    TOTAL_ORDERS INTEGER,
    TOTAL_CART_ADDITIONS INTEGER,
    TOTAL_PAGE_VIEWS INTEGER,
    PRIMARY KEY (METRIC_DATE, CUSTOMER_ID)
);


KAFKA_DB.STREAMING.KAFKA_DAILY_METRICS_GOLD