USE DATABASE KAFKA_DB;
USE SCHEMA STREAMING;

-- See all gold data
SELECT * FROM KAFKA_DAILY_METRICS_GOLD 
ORDER BY METRIC_DATE DESC, CUSTOMER_ID;

-- Summary view
SELECT 
    METRIC_DATE,
    COUNT(DISTINCT CUSTOMER_ID) AS ACTIVE_CUSTOMERS,
    SUM(TOTAL_ORDERS) AS ORDERS,
    SUM(TOTAL_CART_ADDITIONS) AS CART_ADDITIONS,
    SUM(TOTAL_PAGE_VIEWS) AS PAGE_VIEWS,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM KAFKA_DAILY_METRICS_GOLD
GROUP BY METRIC_DATE
ORDER BY METRIC_DATE DESC;