-- Real-time metrics (last hour)
SELECT 
    COUNT(*) AS EVENTS_LAST_HOUR,
    SUM(CASE WHEN EVENT_TYPE = 'PURCHASE' THEN 1 ELSE 0 END) AS ORDERS,
    SUM(CASE WHEN EVENT_TYPE = 'PURCHASE' THEN AMOUNT ELSE 0 END) AS REVENUE
FROM KAFKA_DB.STREAMING.KAFKA_EVENTS_SILVER
WHERE EVENT_TIMESTAMP >= DATEADD(hour, -1, CURRENT_TIMESTAMP());

-- Top customers by revenue
SELECT 
    CUSTOMER_ID,
    SUM(AMOUNT) AS TOTAL_SPENT,
    COUNT(*) AS EVENT_COUNT
FROM KAFKA_DB.STREAMING.KAFKA_EVENTS_SILVER
WHERE EVENT_TYPE = 'PURCHASE'
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SPENT DESC;